---
spring:
  rsocket:
    server:
      port: 7000
      transport: tcp

  main:
    lazy-initialization: false
  devtools:
    livereload:
      enabled: true

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
---

---
spring:
  profiles: prod
  rsocket:
    server:
      port: 7000

  main:
    lazy-initialization: true
  devtools:
    livereload:
      enabled: false

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: off

---